name: Build And Copy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm -v

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: 'LWTlong/blog'
      - run: |
          cd ${{ github.workspace }}
          npm install
          npm run docs:build

      - run: |
          cd ${{ github.workspace }}
          pwd
          cd src/
          ls
          pwd
          cd .vuepress/
          ls
          pwd
          cd dist/
          ls

      - name: cp code to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.HOST_USER }}
          pass: ${{ secrets.HOST_PASSWD }}
          # 由于网路情况，很容易超时，设置为60s
          connect_timeout: 60s
          # 将工作目录下的文件全部拷贝到部署服务器的工作目录
          scp: |
            ./* => /home/long/webapp/blog/dist
